version: "3.7"

services:
  database:
    image: postgres
    container_name: database_real_estate
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=real_estate
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: real_estate_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database
volumes:
  pgdata:
    driver: local